services:
  api:
    build: ./src/Backend.Api
    ports:
      - "5080:8080"

  web:
    build:
      context: ./src/Frontend.AngularJS
      args:
        - VITE_API_BASE=http://api:8080
    ports:
      - "8080:80"
    depends_on:
      - api
